### ISSUE TITLE
[Task] 배포용 미니 클라이언트, 서버 테스트 코드 작성

### ISSUE THREAD

**Issue by Jun0922** [codestates/codecube#130]
## ISSUE
+ Group: `dev ops`
+ Type: `bug`, `feature`, `delete`
+ Detail: 자세한 설명을 작성해 주세요.
## TODO
- [x] CRA로 배포용 리액트앱 생성
- [x] express 미니 노드 서버 생성
- [x] 간단한 버튼과 api 생성 후 콘솔로 연결확인
## Estimated time
- [x] 1.5h
## Labels
Estimated time: `E: 1.5h`
Group : `dev ops`
Sprint: `Sprint__NUMBER__`
Urgency: `High`
