### ISSUE TITLE
[Task] https 환경 구축

### ISSUE THREAD

**Issue by Jun0922** [codestates/codecube#136]
## ISSUE
+ Group: `client`, `server`
+ Type: `bug`, `feature`, `delete`
+ Detail: 자세한 설명을 작성해 주세요.
## TODO
- [x] Client -> cloudfront 웹 브라우저 라우팅 환경 구성
- [x] Server -> ELB 서버 라우팅 환경 구성
- [x] [Option] Lambda를 이용한 서버리스 아키텍트 구성
- [x] Route53 연결 세팅
- [x] https 환경 연결 테스트
## Estimated time
- [x] 8h
## Labels
Estimated time: `E: 8h`
Group : `client`, `server`
Sprint: `Sprint__NUMBER__`
Urgency: `High`
