### ISSUE TITLE
[Task][Back] API Projects(2) 구현

### ISSUE THREAD

**Issue by Jun0922** [codestates/codecube#15]
## ISSUE
> 하나 씩 선택 해주세요.

+ Group: `server`
+ Type: `feature`
+ Detail: Projects(2) API 구현
## TODO
- [ ] PUT/게시물 수정
- [ ] GET/전체 게시글 리스트 요청
- [ ] GET/특정 게시글을 클릭 시 해당 게시글 요청
## Estimated time
> 하나만 선택해 주세요.

- [ ] 3h

## Labels
Estimated time: `E: 3h`
Group : `server`
Sprint: `Sprint__2__`
Urgency: `Middle`
