### ISSUE TITLE
[Task][Back] API Projects(1) 구현

### ISSUE THREAD

**Issue by junu0810** [codestates/codecube#16]
## ISSUE
> 하나 씩 선택 해주세요.

+ Group:  `server`
+ Type: `feature`
+ Detail: API Projects(1)에 대한 controller기능 구현
## TODO
- [ ] DELETE/ 게시글 삭제 
- [ ] POST/ 게시글 작성(추가)
- [ ] 개인 게시글 요청(본인이 적은 게시판 글)
## Estimated time
> 하나만 선택해 주세요.

- [ ] 3h
## Labels
Estimated time: `E: 3h`
Group :  `server`
Sprint: `Sprint__2__`
Urgency: `High`
