### ISSUE TITLE
[Task] [Back] DB 스키마 보완

### ISSUE THREAD

**Issue by cjhmoves33** [codestates/codecube#191]
## ISSUE
+ Group: `server`
+ Type: `feature`

### Detail: 
- DB 전반적인 수정

## TODO
- [x] users 테이블에 Oauth를 구분해줄 칼럼이 필요
- [ ] 기존 DB seed삭제후 bcrypt 적용시켜 재작성
- [ ] 프로젝트 시작/종료 관련해 유저관계도 수정여부 확인

**Comment by Jun0922** [comment]
users table - oauth 칼럼 생성 및 seed oauth 추가 완료
