### ISSUE TITLE
[Task] [Back] 서버코드(API, 기타 콜백) 보완여부 확인

### ISSUE THREAD

**Issue by cjhmoves33** [codestates/codecube#192]
## ISSUE

+ Group: `server`
+ Type: `modify`

+ Detail: 현재 서버코드에서 부분적으로 수정된것만 있기때문에 전체적인 통일이 필요함. 코드 정리/보수.

## TODO
- [ ] 버그나는 API 수정
- [ ] 만들어두고 사용하지않은 API들이 사용가능한 코드인지 검토. 수정필요하면 수정
- [ ] 코드 전체적인 통일성 점검(유지/보수가능한 코드)
- [ ] 로거 보완

**Comment by Jun0922** [comment]
controller - users.js 
전체적으로 버그 api 수정
유지보수가능한 코드로 통일성 점검
로거는 아직 못함
