### ISSUE TITLE
[Task] 로그인 된 상태의 개인 정보 창  컴포넌트 개발

### ISSUE THREAD

**Issue by cjhmoves33** [codestates/codecube#28]
## ISSUE
> 하나 씩 선택 해주세요.

+ Group: `client`
+ Type: `feature`
+ Detail: 자세한 설명을 작성해 주세요.
## TODO
- [x] 프로필사진 컴포넌트
- [x] 기술스택 컴포넌트
- [x] 자기소개 컴포넌트
- [x] 개인 정보수정 버튼
- [x] 수정 상태 여부에 따른 별도 기능구현
- [x] 회원 탈퇴 버튼과 기능
- [ ] 
## Estimated time
> 하나만 선택해 주세요.

- [x] 3h

## Labels
Estimated time: `E: 3h`
Group : `client`
Sprint: `Sprint__NUMBER__`
Urgency: `High`
