### ISSUE TITLE
[Task] 개인 게시판 컴포넌트 개발

### ISSUE THREAD

**Issue by cjhmoves33** [codestates/codecube#29]
## ISSUE
> 하나 씩 선택 해주세요.

+ Group: `client`
+ Type: `feature`
+ Detail: 개인 게시판 컴포넌트 개발
## TODO

- [x] 새 프로젝트 만들기 버튼
- [x] 진행중인 프로젝트 공간
- [x] 신청중인 프로젝트 공간
- [ ] 완료된 프로젝트 공간
- [ ] 게시글 생성 모달창

## Estimated time
> 하나만 선택해 주세요.

- [ ] 3h

## Labels
Estimated time: `E: 3h`
Group : `client`
Sprint: `Sprint__NUMBER__`
Urgency: `High`
