### ISSUE TITLE
[Task] 공개 게시판 컴포넌트 개발

### ISSUE THREAD

**Issue by jres1007** [codestates/codecube#30]
## ISSUE
> 하나 씩 선택 해주세요.

+ Group: `client`
+ Type: `feature`
+ Detail: 공개 게시판 컴포넌트 개발
## TODO
- [x] 공개 게시판 컴포넌트 (타이틀+인원)
- [ ] 게시판에서 게시글 누르면 모달창 열리게 기능 구현
- [ ] 모달창 컴포넌트 제작(타이틀+본문)
- [x] 로그인 안한 상태(인증없이)에서도 이용가능하게 공개 게시판 개발
## Estimated time
> 하나만 선택해 주세요.

- [ ] 3h
## Labels
Estimated time: `E: 3h`
Group : `client`
Sprint: `Sprint__NUMBER__`
Urgency: `Middle`
