### ISSUE TITLE
[Task] 참여/대기중 버튼, 현재 참여인원 컴포넌트 개발

### ISSUE THREAD

**Issue by cjhmoves33** [codestates/codecube#31]
## ISSUE
> 하나 씩 선택 해주세요.

+ Group: `client`
+ Type: `feature`
+ Detail: 참여버튼(참여버튼을 눌렀다면 대기중으로 변환), 현재 참여인원을 보여주는 컴포넌트(인원을 클릭시 인원의 정보를 다른 페이지에서 보여줌)

## TODO
- [ ] 참여 버튼
- [ ] 참여 버튼을 눌렀다면 대기중으로 바뀌고 누를 수 없게 된다.
- [x] 해당 프로젝트에서 현재 참여 확인 인원을 확인할 수 있는 컴포넌트
- [ ] 유저 프로필사진 클릭 시 해당 유저의 정보를 보여주는 새창

## Estimated time
> 하나만 선택해 주세요.

- [ ] 3h

## Labels
Estimated time: `E: 3h`
Group : `client`
Sprint: `Sprint__NUMBER__`
Urgency: `High`
