### ISSUE TITLE
[Task] 게시물 생성버튼, 대기중인원창(수락/거절) 컴포넌트 개발

### ISSUE THREAD

**Issue by jres1007** [codestates/codecube#32]
## ISSUE
> 하나 씩 선택 해주세요.

+ Group: `client`
+ Type: `feature`
+ Detail: 자세한 설명을 작성해 주세요.
## TODO
- [ ] 게시물 생성 컴포넌트
- [ ] 대기중인 인원 컴포넌트
- [ ] 대기중인 인원 수락/거절 
- [ ] 대기중인 인원 프로필 사진 눌렀을시 새 창으로 사용자 정보 보여주기
## Estimated time
> 하나만 선택해 주세요.

- [ ] 3h
## Labels
Estimated time: `E: 3h`
Group : `client`
Sprint: `Sprint__NUMBER__`
Urgency: `Middle`
