### ISSUE TITLE
[Task] Issue Task Card

### ISSUE THREAD

**Issue by cjhmoves33** [codestates/codecube#4]
## ISSUE
> 하나 씩 선택 해주세요.

+ Group: `client`, `server`, `sr` 
+ Type: `bug`, `feature`, `delete`
+ Detail: 자세한 설명을 작성해 주세요.
## TODO
 SR 진행 
 사전 준비: 기획 To Do 리스트
- [x] 1. 프로젝트 기획 및 범위 설정
- [x] 2-A. 프론트엔드 세부 기획 진행
- [x] 2-B. 백엔드 세부 기획 진행
- [x] 3. 위키 및 기능 To Do 리스트 작성
- [x] 4. 태스크 카드 작성 및 분배
- [x] 5. Not To Do 리스트 점검
- [x] 6. 프로젝트 기획 설문조사## Estimated time

> 하나만 선택해 주세요.

## Labels
Estimated time: `E: 1h`
Group : `client`, `server`
Sprint: `Sprint__NUMBER__`
Urgency: `High`, `Middle`, `Low`
